// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr6lxt6MmuM1O5kzYEc6KNcdKedtHNDYc',
    appId: '1:1005760225698:web:2df28aa3709a0970c892fb',
    messagingSenderId: '1005760225698',
    projectId: 'shop-71c8f',
    authDomain: 'shop-71c8f.firebaseapp.com',
    databaseURL: 'https://shop-71c8f-default-rtdb.firebaseio.com',
    storageBucket: 'shop-71c8f.firebasestorage.app',
    measurementId: 'G-L15ZWPYEFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRWfWxjQ_TJL0jbXmnCRFfw_XxsKUO8IE',
    appId: '1:1005760225698:android:76f035b74b573f42c892fb',
    messagingSenderId: '1005760225698',
    projectId: 'shop-71c8f',
    databaseURL: 'https://shop-71c8f-default-rtdb.firebaseio.com',
    storageBucket: 'shop-71c8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCADTQw5NKM5b49VYh90y5dCjoXBjlpUKE',
    appId: '1:1005760225698:ios:05d50218e4544ff1c892fb',
    messagingSenderId: '1005760225698',
    projectId: 'shop-71c8f',
    databaseURL: 'https://shop-71c8f-default-rtdb.firebaseio.com',
    storageBucket: 'shop-71c8f.firebasestorage.app',
    iosClientId: '1005760225698-8tmjmal67ehd2hfhsif6e6lqq1sfvnks.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCADTQw5NKM5b49VYh90y5dCjoXBjlpUKE',
    appId: '1:1005760225698:ios:05d50218e4544ff1c892fb',
    messagingSenderId: '1005760225698',
    projectId: 'shop-71c8f',
    databaseURL: 'https://shop-71c8f-default-rtdb.firebaseio.com',
    storageBucket: 'shop-71c8f.firebasestorage.app',
    iosClientId: '1005760225698-8tmjmal67ehd2hfhsif6e6lqq1sfvnks.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr6lxt6MmuM1O5kzYEc6KNcdKedtHNDYc',
    appId: '1:1005760225698:web:153ff0e3a9d46b47c892fb',
    messagingSenderId: '1005760225698',
    projectId: 'shop-71c8f',
    authDomain: 'shop-71c8f.firebaseapp.com',
    databaseURL: 'https://shop-71c8f-default-rtdb.firebaseio.com',
    storageBucket: 'shop-71c8f.firebasestorage.app',
    measurementId: 'G-R84L80BXTW',
  );
}
